### ISSUE TITLE
Need license information for assests data

### ISSUE THREAD

**Issue by Yashesh123** [stanford-crfm/ecosystem-graphs#120]
Hi Team, Thanks for accumulating model ecosystem data.

I need the license information for this repository, especially for the assets folder. Can any organization freely use those assets' yaml files for analysis purposes?

Thanks

**Comment by rishibommasani** [comment]
Yes, absolutely!

Would love to hear about the use case and how we can make the information more useful (and please cite the work), but the data is fully public for any analyses/etc.
