### ISSUE TITLE
Adding Assets FrictionLess

### ISSUE THREAD

**Issue by vasnt** [stanford-crfm/ecosystem-graphs#121]
What if contributor doesn't know which asset type to be selected?

<img width="479" alt="image" src="https://user-images.githubusercontent.com/117589240/230702720-a54bfb33-be9e-4c63-9bcd-dc08d1819cba.png">

**Comment by rishibommasani** [comment]
We did think about this, but felt declaring the asset type should be a minimal requirement. 

Do you have an example where the asset type is ambiguous or confusing? Happy to change if needed
